---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-proxytypo3org::default]
      - recipe[site-proxytypo3org_test::create_site_to_delete]
    attributes:
      site-proxytypo3org:
        ssl_certificate: wildcard.vagrant
    driver_config:
      network:
      - ["private_network", {ip: "192.168.88.18"}]
      - ["forwarded_port", {guest: 22002, host: 22002, auto_correct: true}]
