---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-9.1

suites:
  - name: default
    run_list:
      - recipe[site-proxytypo3org::default]
      - recipe[site-proxytypo3org_test::create_site_to_delete]
    attributes:
      # we cannot add zabbix-custom-checks, if we (by default) don't install zabbix
      dev_mode: true
      site-proxytypo3org:
        ssl_certificate: wildcard.vagrant
    driver_config:
      network:
      - ["private_network", {ip: "192.168.88.18"}]
  - name: monitoring
    run_list:
      - recipe[site-proxytypo3org::default]
    attributes:
      t3-base:
        flags:
          # test with zabbix
          production: true
      site-proxytypo3org:
        ssl_certificate: wildcard.vagrant
